name: Assign Unassigned Jira Issues

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  assign_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check jq installation
        run: jq --version

      - name: Assign unassigned Jira issues
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          JIRA_ASSIGNEE_ACCOUNT_ID: ${{ secrets.JIRA_ASSIGNEE_ACCOUNT_ID }}
        run: |
          JQL="project=${{ secrets.JIRA_PROJECT_KEY }} AND assignee IS EMPTY"
          RESPONSE=$(curl -s -X GET \
            --url "$JIRA_BASE_URL/rest/api/2/search?jql=$JQL" \
            --user "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
            --header 'Content-Type: application/json')

          ISSUES=$(echo $RESPONSE | jq -r '.issues[] | .key')

          for ISSUE in $ISSUES; do
            echo "Assigning issue $ISSUE to $JIRA_ASSIGNEE_ACCOUNT_ID"
            curl -s -X PUT \
              --url "$JIRA_BASE_URL/rest/api/2/issue/$ISSUE/assignee" \
              --user "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
              --header 'Content-Type: application/json' \
              --data "{\"accountId\": \"$JIRA_ASSIGNEE_ACCOUNT_ID\"}"
          done
