name: Assign Unassigned Jira Issues

on:
  push:
    branches:
      - main

jobs:
  assign-unassigned-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch Unassigned Issues
      id: fetch-issues
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY: "NW" # Replace with your Jira project key
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }} # Your Jira username for assigning issues
      run: |
        JQL_QUERY=$(echo "project=${JIRA_PROJECT_KEY} AND assignee IS EMPTY" | jq -sRr @uri)  # Encode the JQL query
        SEARCH_RESULTS=$(curl --request GET \
          --url "${JIRA_BASE_URL}/rest/api/3/search?jql=${JQL_QUERY}" \
          --user "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
          --header 'Accept: application/json')
        echo "${SEARCH_RESULTS}" > search_results.json
        ISSUE_KEYS=$(echo "${SEARCH_RESULTS}" | jq -r '.issues[].key' | tr '\n' ' ')
        echo "ISSUE_KEYS=${ISSUE_KEYS}" >> $GITHUB_ENV

    - name: Debug: Print ISSUE_KEYS
      run: echo "ISSUE_KEYS=${{ env.ISSUE_KEYS }}"

    - name: Assign Each Issue
      if: env.ISSUE_KEYS != ''
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        ISSUE_KEYS: ${{ env.ISSUE_KEYS }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }} # Your Jira username for assigning issues
      run: |
        for ISSUE_KEY in $ISSUE_KEYS; do
          echo "Assigning issue: ${ISSUE_KEY} to ${JIRA_USERNAME}"
          curl --request PUT \
            --url "${JIRA_BASE_URL}/rest/api/3/issue/${ISSUE_KEY}/assignee" \
            --user "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "name": "'"${JIRA_USERNAME}"'"
            }'
        done
