name: Create Jira Subtask on Field Update

on:
  workflow_dispatch:

jobs:
  create-subtask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Create Jira Subtask
      env:
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
      run: |
        python .github/scripts/create_jira_subtask.py
