name: Transition Jira Issue
 
on:
 workflow dispatch:
 
jobs:
  transition-issue:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Transition Jira Issue
      env:
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_ISSUE_KEY: ${{ secrets.JIRA_ISSUE_KEY }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      run: |
        # Transition the Jira issue to "In Progress"
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic $(echo -n $JIRA_USER_EMAIL:$JIRA_API_TOKEN | base64)" \
          -d '{
            "transition": { "id": "21" } # Replace "31" with the ID of your "In Progress" transition
          }' \
          $JIRA_URL/rest/api/2/issue/$JIRA_ISSUE_KEY/transitions
