name: Close Jira Issues on PR Merge

on:
  workflow dispatch:

jobs:
  close-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: |
          # Extract Jira issue keys from the PR title or body
          # Example: PR title "Fixes PROJ-123: Bug fix"
          JIRA_KEYS=$(echo "${{ github.event.pull_request.title }}" | grep -o 'PROJ-[0-9]\+' || true)
          if [ -z "$JIRA_KEYS" ]; then
            JIRA_KEYS=$(echo "${{ github.event.pull_request.body }}" | grep -o 'PROJ-[0-9]\+' || true)
          fi
          echo "JIRA keys found: $JIRA_KEYS"

          # Loop through each Jira issue key and close it
          for key in $JIRA_KEYS; do
            curl -X POST \
              -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }} \
              -H "Content-Type: application/json" \
              -d '{"transition": {"id": "close"}}' \
              "https://sonashrees.atlassian.net/rest/api/2/issue/${key}/transitions"
          done
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
